"""The database-backed store crudauth keeps its server-side state in.

Built only when ``SESSION_BACKEND`` or ``RATE_LIMITER_BACKEND`` names ``database``, and
``None`` otherwise. Its two tables are declared on ``Base.metadata``, so
``CREATE_TABLES_ON_STARTUP`` creates them and ``alembic revision --autogenerate`` writes
them beside the project's own.
"""

from crudauth import DatabaseStore
from sqlalchemy import MetaData

from ..config.enums import RateLimiterBackend, SessionBackend
from ..config.settings import settings
from ..database.session import Base, get_session_factory


def _is_selected() -> bool:
    """Whether a setting puts sessions or the lockout counters in the database."""
    return settings.SESSION_BACKEND == SessionBackend.DATABASE or settings.RATE_LIMITER_BACKEND == RateLimiterBackend.DATABASE


def build_store(metadata: MetaData | None = None) -> DatabaseStore | None:
    """The store the settings selected, on the app's own engine.

    Args:
        metadata: Where to declare the two tables. The project's own by default, which is
            what puts them in ``create_all`` and in an autogenerated migration.
    """
    if not _is_selected():
        return None

    return DatabaseStore(get_session_factory(), metadata=metadata if metadata is not None else Base.metadata)


database_store = build_store()
