"""``bp deploy generate``: what it writes, and what a dry run leaves alone."""

import pytest
from typer.testing import CliRunner

from cli.commands import deploy

runner = CliRunner()


@pytest.fixture
def project(tmp_path):
    """A directory that looks enough like a project for the command to run in."""
    (tmp_path / "backend").mkdir()
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'example'\n")

    return tmp_path


def test_a_dry_run_writes_nothing_and_creates_no_directory(project):
    target = project / "generated"

    result = runner.invoke(deploy.app, ["nginx", "-o", str(target), "--dry-run"])

    assert result.exit_code == 0, result.output
    assert "would write" in result.output
    assert not target.exists()


def test_a_dry_run_over_an_existing_file_asks_nothing(project):
    compose = project / "docker-compose.yml"
    compose.write_text("keep me\n")

    result = runner.invoke(deploy.app, ["prod", "-o", str(project), "--dry-run"], input="")

    assert result.exit_code == 0, result.output
    assert compose.read_text() == "keep me\n"
    assert "Overwrite" not in result.output


def test_generating_writes_the_compose_file(project):
    result = runner.invoke(deploy.app, ["prod", "-o", str(project), "--yes"])

    assert result.exit_code == 0, result.output
    assert (project / "docker-compose.yml").read_text().startswith("# Generated by")
