"""``bp deploy generate``: what it writes, and what a dry run leaves alone."""

import pytest
from typer.testing import CliRunner

from cli.commands import deploy

runner = CliRunner()


@pytest.fixture
def project(tmp_path):
    """A directory that looks enough like a project for the command to run in."""
    (tmp_path / "backend").mkdir()
    (tmp_path / "pyproject.toml").write_text("[project]\nname = 'example'\n")

    return tmp_path


def test_a_dry_run_writes_nothing_and_creates_no_directory(project):
    target = project / "generated"

    result = runner.invoke(deploy.app, ["nginx", "-o", str(target), "--dry-run"])

    assert result.exit_code == 0, result.output
    assert "would write" in result.output
    assert not target.exists()


def test_a_dry_run_over_an_existing_file_asks_nothing(project):
    compose = project / "docker-compose.yml"
    compose.write_text("keep me\n")

    result = runner.invoke(deploy.app, ["prod", "-o", str(project), "--dry-run"], input="")

    assert result.exit_code == 0, result.output
    assert compose.read_text() == "keep me\n"
    assert "Overwrite" not in result.output


def test_generating_writes_the_compose_file(project):
    result = runner.invoke(deploy.app, ["prod", "-o", str(project), "--yes"])

    assert result.exit_code == 0, result.output
    assert (project / "docker-compose.yml").read_text().startswith("# Generated by")


@pytest.mark.parametrize(
    "subnet",
    [
        "*",
        "0.0.0.0/0",
        "10.0.0.0/7",
        "172.31.240.1/24",
        "not-a-subnet",
        "172.31.240.0/33",
        "::/0",
        "fd00::/8",
        "fd00::/47",
        "fd00::1/48",
    ],
)
def test_a_subnet_that_trusts_too_much_is_refused(project, subnet: str):
    """The range decides whose forwarded headers the app believes."""
    result = runner.invoke(deploy.app, ["nginx", "-o", str(project), "--internal-subnet", subnet, "--yes"])

    assert result.exit_code == 1
    assert "--internal-subnet" in result.output
    assert not (project / "docker-compose.yml").exists()


@pytest.mark.parametrize("subnet", ["172.31.240.0/24", "10.1.2.0/28", "192.168.0.0/16", "fd00::/48", "fd00::/64"])
def test_a_subnet_that_names_a_network_is_accepted(project, subnet: str):
    result = runner.invoke(deploy.app, ["nginx", "-o", str(project), "--internal-subnet", subnet, "--yes"])

    assert result.exit_code == 0, result.output
    assert f'- subnet: "{subnet}"' in (project / "docker-compose.yml").read_text()
