"""Importing the model modules, so ``Base.metadata`` knows every table."""

import importlib
import pkgutil

from ...wiring.tables import TABLE_MODULES

MODELS_PACKAGE = "src.modules"


def import_models(package_name: str = MODELS_PACKAGE) -> None:
    """Import every module under ``package_name`` and every module the wiring lists.

    A feature that declares a table outside ``src/modules`` — the accounts feature's
    database store — is named in ``wiring/tables.py``, so a migration autogenerated from
    ``Base.metadata`` describes it without depending on a route module to import it.
    """
    package = importlib.import_module(package_name)
    for _, module_name, _ in pkgutil.walk_packages(package.__path__, package.__name__ + "."):
        importlib.import_module(module_name)

    for module_name in TABLE_MODULES:
        importlib.import_module(module_name)
